[package]
name = "egui_render_glow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glow = { version = "0.11" }
egui_backend = { path = "../egui_backend" , features = ["egui_bytemuck"]}
intmap = { version = "2" }
bytemuck = { version = "1" }
