[package]
name = "egui_window_winit"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "winit window integration for egui"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = { version = "0.27", features = [] }
egui_backend = { version = "0.1", path = "../egui_backend" }
glutin = { version = "0.29" }
