[package]
name = "etk"
version = "0.2.0"
edition = "2021"
description = "Egui's toolkit"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
egui_backend = { path = "crates/egui_backend", features = ["winit", "wgpu"]}
egui = { version = "*" }
console_error_panic_hook = "0.1.6"
tracing-wasm = "*"

# [dev-dependencies]
# egui_backend = { path = "crates/egui_backend", features = ["winit", "wgpu"]}

# [target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
# egui = { version = "0.19.0" }
# tracing-subscriber = { version = "*", features = ["env-filter"] }
# tracing = { version = "*" }


[workspace]
members = ["crates/egui_backend"]
