[package]
name = "egui_render_wgpu"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "wgpu render integration for egui"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui_backend = { version = "0.2", path = "../egui_backend", features = ["egui_bytemuck"] }
intmap = { version = "2" }
bytemuck = { version = "1" }
wgpu = { version = "0.13", features = ["webgl"]}
pollster = { version = "0.2" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom ={ version = "*", features = ["js"]} # because egui -> ahash issue https://github.com/emilk/egui/issues/2009