[package]
name = "egui_window_tao"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui_backend = { version = "0.2", path = "../egui_backend" }
tao = { version = "0.12.2", features = [] }
